# Generated by Django 4.2.7 on 2023-11-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_slug',
            new_name='news_slug',
        ),
    ]
