# Generated by Django 5.0.4 on 2024-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updates_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
